disabled_rules:
 - identifier_name

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 20